-- Add marketing array fields to cursos table
ALTER TABLE public.cursos
ADD COLUMN publico_objetivo text[] DEFAULT '{}'::text[],
ADD COLUMN que_vas_a_lograr text[] DEFAULT '{}'::text[];

-- Create testimonios_cursos table
CREATE TABLE IF NOT EXISTS public.testimonios_cursos (
    id bigint generated by default as identity primary key,
    curso_id bigint references public.cursos(id) on delete cascade,
    nombre text not null,
    texto text not null,
    foto_url text,
    orden integer default 0,
    activo boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
ALTER TABLE public.testimonios_cursos ENABLE ROW LEVEL SECURITY;

-- Create policies for testimonios_cursos
CREATE POLICY "Testimonios son visibles para todos" ON public.testimonios_cursos
    FOR SELECT USING (true);

-- Allow admins to manage testimonios (assuming they use service role or similar setup, 
-- but let's add a permissive policy for authenticated users or just rely on service role)
CREATE POLICY "Admins pueden gestionar testimonios" ON public.testimonios_cursos
    FOR ALL USING (auth.role() = 'authenticated');
